[config]
schemaVersion = "0.0.1"

[package]
namespace = "loaforc"
name = "loaforcsSoundAPI_Beta"
description = "Deprecated, the main package has been updated."
websiteUrl = "https://github.com/loaforcsSoundAPI/loaforcsSoundAPI"
versionNumber = "2.2.2"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
loaforc-loaforcsSoundAPI = "2.0.0"

[build]
icon = "./icon.png"
outdir = "../Packages"

[[build.copy]]
source = "README.md"
target = "README.md"

[publish]
repository = "https://thunderstore.io"
communities = [ "riskofrain2", ]
[publish.categories]
riskofrain2 = [ "items", "skills", ]