[config]
schemaVersion = "0.0.1"

[package]
namespace = "loaforc"
name = "loaforcsSoundAPI"
description = "A general use library to replace sounds in Unity games."
websiteUrl = "https://github.com/loaforcsSoundAPI/loaforcsSoundAPI"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "./icon.png"
readme = "../../README.md"
outdir = "../../Packages"

[[build.copy]]
source = "../bin/Release/netstandard2.1/me.loaforc.soundapi.dll"
target = "BepInEx/plugins/loaforcsSoundAPI/"

[publish]
repository = "https://thunderstore.io"
communities = [ "riskofrain2", ]
[publish.categories]
riskofrain2 = [ "items", "skills", ]